### ISSUE TITLE
vim-cpywrite cost longer time than other plugins.

### ISSUE THREAD

**Issue by cxwx** [rdipardo/vim-cpywrite#1]
using `vim --startuptime file`
it take 230ms to load this plugin, much longer than other plugins.

**Comment by rdipardo** [comment]
Yikes!

I repeated your steps and got similar or worse results with vim and neovim on a virtualized Ubuntu image. 
The output is attached for anybody who wants to tackle this issue.

```bash
srvadmin@ubuntu:~$ uname -a
Linux ubuntu 4.4.0-184-generic #214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

[vim-bench.log](https://github.com/rdipardo/vim-cpywrite/files/4978473/vim-bench.log)
[nvim-bench.log](https://github.com/rdipardo/vim-cpywrite/files/4978475/nvim-bench.log)

**Comment by rdipardo** [comment]
I traced the problem to the Python feature tests. According to the help topic at [`:help has-python`](https://vimhelp.org/if_pyth.txt.html):

> when Python 2 and 3 are both available and loaded
> dynamically, these has() calls will try to load them

The [newest build](https://github.com/rdipardo/vim-cpywrite/commit/494529e7fd8a#diff-8f53b23c60d92d81e3da66f14d8f2ccaR8) holds off on calling `has(python)` until the first command call, and the error reporting function won't get loaded unless it's actually needed. 

You may notice it takes longer to update the buffer on the first go, but your editor will start up [a lot quicker](https://travis-ci.com/github/rdipardo/vim-cpywrite/jobs/370516437#L613):

```bash
awk '/.*plugin\/cpywrite\.vim.*$/' nvim_bench.log vim_bench.log
014.314  000.089  000.089: sourcing ./plugin/cpywrite.vim
052.832  000.082  000.082: sourcing ./plugin/cpywrite.vim
```
I'll be merging the  `autoload`ed version soon.

Thanks for your help!
